#include "rwmake.ch"
#Include "Protheus.ch"

//------------------------------------------------------------------------------------------
/*/{Protheus.doc} FISTRFNFE
Permite a manuten??o de dados armazenados em .

@author    TOTVS | Developer Studio - Gerado pelo Assistente de C?digo
@version   1.xx
@since     23/07/2018
/*/
//------------------------------------------------------------------------------------------


User Function FISTRFNFE

	aadd(aRotina,{"* Imprimir Boletos","U_NMFINM01()",0,2,0,NIL})
	//aadd(aRotina,{'* Pre-DANFE'	  	  ,'U_NMFATM01()' 	 ,0,3,0,NIL})

Return
